#!/usr/bin/env bash
# Writes tmp/seed-run.js, a browser-console script that plants a part-finished Yellow run in
# localStorage, for testing the sync banner and the write-through without playing the game.
#
#   tools/console/regenerate-seed.sh          # 80%, the default
#   tools/console/regenerate-seed.sh 0.25     # a quarter of the way in
#
# Ids are read from the live model on every run rather than a list checked in beside it, so a
# seed can never point at a tick the walkthrough has since renamed.
set -e
cd "$(dirname "${BASH_SOURCE[0]}")/../.."

FRACTION="${1:-0.8}" bin/rails runner - <<'RUBY'
fraction = ENV.fetch("FRACTION").to_f
out = "tmp/seed-run.js"

ticks = lambda do |loc|
  rows = loc.steps.flat_map { |step| step.items.map(&:tick) + step.hidden.map(&:tick) }
  rows += loc.later.map(&:tick) + loc.trainers.map(&:tick) + loc.trades.map(&:tick)
  rows += [ loc.gym, loc.dojo ].compact.flat_map { |h| h.trainers.map(&:tick) << h.leader.tick }
  rows.compact
end
part = ->(list) { list.first((list.size * fraction).round) }

stops = Walkthrough.find!("yellow").legs.flat_map(&:locations)
ordered = stops.flat_map(&ticks).uniq
species = stops.flat_map { |loc| loc.wild_encounters.map(&:dex) }.uniq
marks = part.call(ordered)
caught = part.call(species)

# Grouped by map: the flat list of ids is half again as many bytes to paste.
by_map = marks.group_by { |id| id.split("/").first }
  .transform_values { |ids| ids.map { |id| id.split("/", 2).last } }

File.write(out, <<~JS)
  // Generated by tools/console/regenerate-seed.sh. Plants #{(fraction * 100).round}% of a Yellow
  // run in this browser, in walk order: everything up to #{marks.last.split('/').first} ticked.
  //
  //   seedRun()                   #{marks.size} marks and #{caught.size} species
  //   seedRun({ species: false }) marks only
  //
  // Run it LOGGED OUT: the banner reads localStorage on the way in, so seed before you sign in.
  function seedRun({ species = true } = {}) {
    const BY_MAP = #{JSON.pretty_generate(by_map).gsub("\n", "\n  ")};
    const SPECIES = #{caught.to_json};
    const collected = {};
    Object.entries(BY_MAP).forEach(([map, things]) => {
      things.forEach((thing) => { collected[`${map}/${thing}`] = true; });
    });
    const state = { v: 2, collected: { yellow: collected }, caught: {}, bodies: {} };
    if (species) {
      state.caught.yellow = Object.fromEntries(SPECIES.map((dex) => [dex, true]));
      state.bodies.yellow = Object.fromEntries(SPECIES.map((dex) => [dex, 1]));
    }
    localStorage.setItem("porynet.progress", JSON.stringify(state));
    window.dispatchEvent(new CustomEvent("porynet:progress", { detail: { changed: {} } }));
    const marks = Object.keys(collected).length;
    const held = Object.keys(state.bodies.yellow || {}).length;
    console.log(`localdb seeded: ${marks} marks, ${held} species, ${marks + held} records`);
    return { marks, species: held };
  }

  seedRun();
JS

puts "wrote #{out}"
puts "  #{marks.size} of #{ordered.size} marks, #{caught.size} of #{species.size} species"
puts "  #{marks.size + caught.size} records, " \
     "#{(marks.size / 64.0).ceil + (caught.size / 64.0).ceil} batches at #{Progress::Sync::MAX_KEYS} keys"
RUBY
